global using BuildingBlocks.Auth.Middlewares;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handlers;
global using Carter;
global using EventService.API;
global using EventService.API.Entities;
global using FluentValidation;
global using Marten;
global using MediatR;