global using BuildingBlocks.Auth.Middlewares;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handlers;
global using Carter;
global using FluentValidation;
global using Marten;
global using Mapster;
global using MediatR;
global using NotificationService.API;